const int led1 = 1;
const int led2 = 2;
const int led3 = 3;
const int led4 = 4;
const int led5 = 5;
const int led6 = 6;
const int led7 = 7;
const int led8 = 8;
const int led9 = 9;
const int led10 = 10;
void setup() {
  pinMode(led1, OUTPUT);
  pinMode(led2, OUTPUT);
  pinMode(led3, OUTPUT);
  pinMode(led4, OUTPUT);
  pinMode(led5, OUTPUT);
  pinMode(led6, OUTPUT);
  pinMode(led7, OUTPUT);
  pinMode(led8, OUTPUT);
  pinMode(led9, OUTPUT);
  pinMode(led10, OUTPUT);
}
void loop() {
  int i = 1000;
  digitalWrite(led1, LOW);
  digitalWrite(led2, LOW);
  digitalWrite(led3, LOW);
  digitalWrite(led4, LOW);
  digitalWrite(led5, LOW);
  digitalWrite(led6, LOW);
  digitalWrite(led7, LOW);
  digitalWrite(led8, LOW);
  digitalWrite(led9, LOW);
  digitalWrite(led10, LOW);
  delay(i);
  digitalWrite(led6, HIGH);
  digitalWrite(led2, HIGH);
  digitalWrite(led5, HIGH);
  digitalWrite(led3, HIGH);
  digitalWrite(led7, HIGH);
  digitalWrite(led8, HIGH);
  delay(i);
  digitalWrite(led7, HIGH);
  digitalWrite(led1, HIGH);
  digitalWrite(led5, HIGH);
  digitalWrite(led4, HIGH);
  digitalWrite(led3, HIGH);
  digitalWrite(led2, HIGH);
  digitalWrite(led7, LOW);
  digitalWrite(led4, LOW);
  digitalWrite(led3, LOW);
  delay(i);
  digitalWrite(led2, HIGH);
  digitalWrite(led7, HIGH);
  digitalWrite(led3, HIGH);
  digitalWrite(led6, LOW);
  delay(i);
  digitalWrite(led2, LOW);
  digitalWrite(led1, LOW);
  digitalWrite(led1, HIGH);
  digitalWrite(led4, HIGH);
  digitalWrite(led9, HIGH);
  digitalWrite(led8, LOW);
  delay(i);
  digitalWrite(led7, LOW);
  digitalWrite(led5, LOW);
  digitalWrite(led4, LOW);
  digitalWrite(led3, LOW);
  digitalWrite(led1, HIGH);
  digitalWrite(led2, HIGH);
  delay(i);
  digitalWrite(led7, HIGH);
  digitalWrite(led4, HIGH);
  digitalWrite(led6, HIGH);
  digitalWrite(led3, HIGH);
  delay(i);
  digitalWrite(led7, HIGH);
  digitalWrite(led1, HIGH);
  digitalWrite(led5, HIGH);
  digitalWrite(led3, HIGH);
  digitalWrite(led9, LOW);
  digitalWrite(led10, HIGH);
  digitalWrite(led4, LOW);
  delay(i);
  digitalWrite(led4, HIGH);
  delay(i);
  digitalWrite(led6, LOW);
  digitalWrite(led5, LOW);
  digitalWrite(led4, LOW);
  digitalWrite(led3, LOW);
  delay(i);
  digitalWrite(led5, HIGH);
  digitalWrite(led3, HIGH);
  digitalWrite(led4, HIGH);
  digitalWrite(led1, LOW);
  digitalWrite(led6, HIGH);
  delay(i);
  digitalWrite(led4, LOW); //5 
  digitalWrite(led6, HIGH);
  digitalWrite(led2, HIGH);
  digitalWrite(led1, LOW);
  digitalWrite(led3, HIGH);
  delay(i);
  digitalWrite(led1, HIGH);//4
  digitalWrite(led5, HIGH);
  digitalWrite(led2, HIGH);
  digitalWrite(led7, LOW);
  digitalWrite(led4, LOW);
  digitalWrite(led3, LOW);
  delay(i);
  digitalWrite(led6, LOW); //3
  digitalWrite(led3, HIGH);
  digitalWrite(led7, HIGH);
  delay(i);
  digitalWrite(led2, LOW); //2
  digitalWrite(led4, HIGH);
  delay(i);
  digitalWrite(led7, LOW); //1
  digitalWrite(led5, LOW);
  digitalWrite(led4, LOW);
  digitalWrite(led3, LOW);
  digitalWrite(led2, HIGH);
  delay(i);
  digitalWrite(led1, LOW);
  digitalWrite(led2, LOW);
  digitalWrite(led3, LOW);
  digitalWrite(led4, LOW);
  digitalWrite(led5, LOW);
  digitalWrite(led6, LOW);
  digitalWrite(led7, LOW);
  digitalWrite(led8, LOW);
  digitalWrite(led9, LOW);
  digitalWrite(led10, LOW);
  delay(i);
}